### numpy (Numerical Python)
- Open Source Python 라이브러리
- 다차원배열 (ndarray)와 행렬 연산을 수행할 수 있는 구조로 되어있다.

#### 넘파이는 넘파이배열(ndarray) 라는 자료구조를 사용.
- 벡터나 행렬등의 연산을 쉽게 빠르게 수행. 

In [2]:
# numpy 설치
!(주피터에서 사용) pip install numpy

pip��(��) ������� �ʾҽ��ϴ�.


In [3]:
# numpy array는 numpy array끼리 연산이 가능
# 0 ~ 9까지 파이썬 리스트를 만들어보자
pa = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] # pa = list(range(10))
print(pa)

pb = pa
print(pa + pb) # list 연산

import numpy as np
na = np.arange(10) # 리스트 생성
na # 1차원 array 
nb = na

# Broadcasting
print(na + nb) # list 내 연산
print(na * 4 - 1)
print(pa * 4) # list 복제

print(type(na))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0  2  4  6  8 10 12 14 16 18]
[-1  3  7 11 15 19 23 27 31 35]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'numpy.ndarray'>


## Numpy 배열
- 모든 배열의 값이 기본적으로 같은 타입
- 각 차원(Dimension)을 축(axis)로 표현

In [14]:
[1,2,3] # 1차원 배열

# shape(2,3)형태
[[1,2,3],
 [4,5,6]] # 2차원 배열

# shape(3,3)
[[1,2,3],
 [4,5,6],
 [7,8,9]]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
# axis0 = 2 axis1 = 3
# shape(2,3)
a = [[1,2,3],[4,5,6]]
b = np.array(a)
print(b, type(b))
print(b.shape)
b[1,2] # 특정 colum값 추출 

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
(2, 3)


6

In [1]:
a = np.arange(10, dtype = np.float32)
print(a, a.dtype)

NameError: name 'np' is not defined

In [5]:
a = np.arange(12)
b = a.reshape(2,6)
print(b)
print(a)
c = a.reshape(2,2,3)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [13]:
a = np.arange(12).reshape(3,4)
print(a)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# numpy 배열 대표 속성 값
- shape: 배열의 각축(axis)의 크기
- ndim: 축의 개수(차원의 개수)
- dtype: 각 요소의 타입
- itemsize: 각 요소의 타입의 크기
- size: 전체 요소의 개수

In [15]:
print(a)
print()
print(a.shape)
print()
print(a.ndim) # 배열 앞의 대괄호 개수로 차원 크기 추정 가능
print()
print(a.itemsize)
print()
print(a.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

(3, 4)

2

4

12


## 넘파이 배열 생성 방법
- np.array() 이용하여 tuple이나 list를 통해 ndarray를 생성

In [20]:
a = np.array([1,2,3])
print(a, type(a))

b= np.array([1.2, -3.5, 5.1])
print(b, type(b), b.dtype)

[1 2 3] <class 'numpy.ndarray'>
[ 1.2 -3.5  5.1] <class 'numpy.ndarray'> float64


In [28]:
arr = np.array([1,2,3,4,5])
arr.dtype

# 타입 변경 astype
arr_float = arr.astype(np.float64)
print(arr_float.dtype)

print(arr.dtype) # 원본에는 변경 사항 없음

float64
int32


In [33]:
num_str = np.array([1.234, -2.29, 1000])
print(num_str, num_str.dtype)
num_str = num_str.astype(np.string_)
print(num_str, num_str.dtype)

arr_str = np.array(list(map(lambda x: x.decode(), num_str))) # 데이터 숫자가 많을 때, for문보다 속도가 빠름
arr_str = np.array([x.decode() for x in num_str])

# decoded_nums = []
# for num in num_str:
#     decoded_nums.append(num.decode())
# np_array = np.array(decoded_nums)

print(arr_str, type(arr_str),  arr_str.dtype)

[   1.234   -2.29  1000.   ] float64
[b'1.234' b'-2.29' b'1000.0'] |S32
['1.234' '-2.29' '1000.0'] <class 'numpy.ndarray'> <U6


In [40]:
print(np.empty((2,3)))
np.full((2,3), 5)
a = np.ones((2,3,4))
print(a.shape)
a = np.full((2,3,4), 5)
a

[[2.12199579e-314 6.36598737e-314 1.06099790e-313]
 [1.48539705e-313 1.90979621e-313 2.33419537e-313]]
(2, 3, 4)


array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

- np.arange() : n - 1만큼 숫자 생성
- np.linspace() : n등분만큼 숫자 생성

In [47]:
print(np.arange(10,30))
print(np.arange(10,30,5))

print()
print(np.linspace(0, 99, 10)) # 10등분으로 나뉘어서 표현


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[10 15 20 25]

[ 0. 11. 22. 33. 44. 55. 66. 77. 88. 99.]


In [56]:
# 0부터 1까지 0.25 step으로 출력
print(np.arange(0, 1+0.25, 0.25))

# 0부터 1까지 5등분으로 출력
print(np.linspace(0,1,5))


[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]


In [62]:
# 0부터 5까지 1차원 array를 생성
a = np.arange(12) # 단순 1차원 배열 생성
print(a, a.ndim, a.shape)
# 4, 3의 shape으로 2차원 배열 출력
b = a.reshape(4,3) # shape 변경
print(b, b.ndim, b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1 (12,)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 2 (4, 3)


In [64]:
# arange를 활용해서 (2,3,4)의 3차원 배열을 만드시오
a = np.arange(24).reshape(2,3,4)
print(a, a.ndim, a.shape)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 3 (2, 3, 4)


# Numpy 기본연산
- 차원(축=axis)기준으로 행렬 내에 같은 위치에 있는 원소끼리 연산을 하는 방식


In [79]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [69]:
c = a - b
print(c)

[10 19 28 37]


In [86]:
c = b**2 # 원본은 그대로이기 때문에 따로 저장
print(c)

[0 1 4 9]


In [93]:
c = a < 25 # boolean 결과 값이 표현
a[a > 25] # 조건으로 원하는 값만 출력 가능 True는 취하고 False는 버림
print(a)
print(a[a>25])

[10 20 30 40]
[30 40]


In [110]:
# 3x4 배열을 만들고
a = np.arange(12).reshape(3,4)
print(a)
# [Bob, Jeo, Bob]를 가진 1차원 어레이를 선언
a_str = np.array(['Bob', 'Jeo', 'Bob'])
print(a_str)
# Bob에 해당하는 인덱스만 3X4 어레이에서 출력
a[a_str == 'Bob'] # 원본 자체는 변하지 않음
b = a[a_str == 'Bob']
print(b)
c = a[a_str == 'Jeo']
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
['Bob' 'Jeo' 'Bob']
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[4 5 6 7]]


In [121]:
d = a[a_str == 'Bob', 1:3]
print(d)

[[ 1  2]
 [ 9 10]]


In [139]:
# Bob에 해당하는 행에 1행만 출력하고자 한다면
e = a[a_str == 'Bob']
print(e[1][1:3])
names = np.array(['Bob', 'Jeo', 'Wil']) 
mask = (names == 'Bob') | (names == 'Wil')
print(mask)
a[mask]

[ 9 10]
[ True False  True]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [152]:
# 2,3
# 10, 11
# 위의 값들을 0으로 변경
b = a[mask]
print(b, type(b))
b[:,2:] = 0
b

[[ 0  1  2  3]
 [ 8  9 10 11]] <class 'numpy.ndarray'>


array([[0, 1, 0, 0],
       [8, 9, 0, 0]])

In [154]:
a, names

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array(['Bob', 'Jeo', 'Wil'], dtype='<U3'))

In [216]:
a = np.arange(12).reshape(3,4)
names = np.array(['Bob', 'Jeo', 'Wil']) 
b = a[names != 'Bob'] 
c = b[0, 0:] = 7
print(c)


7


In [167]:
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr1, arr2
arr1 < arr2

array([[False,  True, False],
       [ True, False,  True]])

In [187]:

# 8x4 빈 배열을 하나 만들고 
# 각 행마다 1행에는 0의 값을, 2행에는 1의 값을 ... 넣어보자
arr = np.zeros((8,4))

for i in range(len(arr)):
    arr[i] = i 

print(arr)
print(arr[[4,0,7,1,1,1,1,1]]) # 원하는 행 인덱싱 가능
print(arr[[-4, -5, -6]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [0. 0. 0. 0.]
 [7. 7. 7. 7.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [2. 2. 2. 2.]]


### 다중 정수배열 인덱싱은 항상 1차원 배열을 리턴

In [194]:
arr = np.arange(256).reshape(8,4,2,2,2)
print(arr)
arr[[1,5,7,2],[0,3,1,2],[1,1,1,1],[1,1,1,1],[1,1,1,1]] # (1,0), (5,3), (7,1), (2,2)

[[[[[  0   1]
    [  2   3]]

   [[  4   5]
    [  6   7]]]


  [[[  8   9]
    [ 10  11]]

   [[ 12  13]
    [ 14  15]]]


  [[[ 16  17]
    [ 18  19]]

   [[ 20  21]
    [ 22  23]]]


  [[[ 24  25]
    [ 26  27]]

   [[ 28  29]
    [ 30  31]]]]



 [[[[ 32  33]
    [ 34  35]]

   [[ 36  37]
    [ 38  39]]]


  [[[ 40  41]
    [ 42  43]]

   [[ 44  45]
    [ 46  47]]]


  [[[ 48  49]
    [ 50  51]]

   [[ 52  53]
    [ 54  55]]]


  [[[ 56  57]
    [ 58  59]]

   [[ 60  61]
    [ 62  63]]]]



 [[[[ 64  65]
    [ 66  67]]

   [[ 68  69]
    [ 70  71]]]


  [[[ 72  73]
    [ 74  75]]

   [[ 76  77]
    [ 78  79]]]


  [[[ 80  81]
    [ 82  83]]

   [[ 84  85]
    [ 86  87]]]


  [[[ 88  89]
    [ 90  91]]

   [[ 92  93]
    [ 94  95]]]]



 [[[[ 96  97]
    [ 98  99]]

   [[100 101]
    [102 103]]]


  [[[104 105]
    [106 107]]

   [[108 109]
    [110 111]]]


  [[[112 113]
    [114 115]]

   [[116 117]
    [118 119]]]


  [[[120 121]
    [122 123]]

   [[124 125]
    [126 127]]]]





array([ 39, 191, 239,  87])

### 기본연산
- * : 각각 원소끼리 곱셈
- @ : 행렬 곱셈


In [211]:
A = np.array(np.arange(4)).reshape(2,2)
B = A
B
print(A)
print(B)
print(A*B)
print(A@B)


[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[0 1]
 [4 9]]
[[ 2  3]
 [ 6 11]]


In [217]:
a = np.ones(3, dtype = np.int32)
b= np.linspace(0, np.pi, 3)
b.dtype
c = a + b 
c, c.dtype # 연산을 했을 때 타입형이 큰 것으로 적용 int < float < complex

(array([1.        , 2.57079633, 4.14159265]), dtype('float64'))

### 집계함수
- sum()
- min()
- max()
- argmax() : 모든 요소 중 최대값의 인덱스
- cumsum() : 모든 요소의 누적합
- mean() : 평균

In [227]:
# 0 ~ 7까지 제곱된 값을 2, 4크기로 출력
a = np.arange(8).reshape(2,4)**2 #를 붙여도 가능

# print(a)
# print(a.sum())
# print(a.min())
# print(a.argmax())
# print(a.argmin())
# print(a.cumsum())

arr = np.arange(9).reshape(3,3)
print(arr.cumsum(axis=1))
print(arr)
arr.sum(axis=0)

[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([ 9, 12, 15])

### 넘파이 범용함수 (universal function)


In [229]:
B = np.array([1,4,9])
np.sqrt(B)

array([1., 2., 3.])

### Numpy 인덱싱과 슬라이싱

In [256]:
a = np.arange(10)**2
print(a)
print(a[2:5]) # 슬라이싱
print(a[::-1])

# 0,4,9를 출력하시오
print(a[0:6:2]) # 간격설정 가능
a[0:5:2] = 1000
print(a)

arr = a[5:8]
print(arr)

[ 0  1  4  9 16 25 36 49 64 81]
[ 4  9 16]
[81 64 49 36 25 16  9  4  1  0]
[ 0  4 16]
[1000    1 1000    9 1000   25   36   49   64   81]
[25 36 49]


In [266]:
arr[1] = 1234
print(arr)
print(a) # 원본 값도 변경 된다.

[  25 1234   49]
[1000    1 1000    9 1000   25 1234   49   64   81]


- 배열 슬라이스는 새로운 객체를 만드는 것이 아닌 배열에 대한 view를 가진다.
- 즉 잘라낸 배열에 값을 변경 시(대입연산자) 원본 값도 변경된다.

In [268]:
arr[:] = 500
a

array([1000,    1, 1000,    9, 1000,  500,  500,  500,   64,   81])

In [275]:
a = np.arange(10)**2
arr = a[5:8].copy() # copy를 해줘야 원본이 유지 됨.
print(arr)

arr[:] == -100
print(a) # 원본 데이터 보존


[25 36 49]
[ 0  1  4  9 16 25 36 49 64 81]


In [278]:
# 1~9까지 3x3 배열을 만들자

arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [284]:
arr2d[0] # 1차원 배열
print(arr2d[0][1]) #1
print(arr2d[0, 1]) #2

2
2


In [300]:
# 1~12까지 2x2x3 행렬 생성
arr3d = np.arange(1,13).reshape(2,2,3)
print(arr3d) # 3차원 
print(arr3d[0][1]) #1
print(arr[0, 1]) #2
print(arr[1, 0])
print(arr[1, 0, 1])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[4 5 6]
[4 5 6]
[7 8 9]
8


In [306]:
# 원본 회손없이 첫 번째 2x3행렬에 100으로 변경하고자 한다.
old = arr3d.copy()
old[0] = 100
print(old)

# 10 11 출력
print(old[1][1][0:2])
print(old[1, 1, 0:2])

[[[100 100 100]
  [100 100 100]]

 [[  7   8   9]
  [ 10  11  12]]]
[10 11]
[10 11]


In [6]:
a= np.arange(8)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49])

In [7]:
mask = np.array([1, 1, 3, 5])
a[mask]

array([ 1,  1,  9, 25])

In [10]:
mask2d = np.array([[3,4],[2,5]])
mask2d

array([[3, 4],
       [2, 5]])

In [14]:
a[mask2d].shape

(2, 2)

In [15]:
a = np.arange(12).reshape(3,4)
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [17]:
a[a > 4] = 0 
a


array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

### numpy 크기(차원) 변경
reval : 1차원 변경
reshape : 지정한 차원으로 변경
T : 전치(transpose)

In [25]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a.T #전치 행렬

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [38]:
a = a.T

In [41]:
a[:2, 1:]

array([[4, 8],
       [5, 9]])

In [42]:
a

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [63]:
print(a[3: , : ].shape)
print(a[-1].shape)

print(a[:,0:2].shape)
print(a[1,0:2])
a[1:2, :2].shape # 2차원 array

(1, 3)
(3,)
(4, 2)
[1 5]


(1, 2)

In [65]:
a[:2]

array([[0, 4, 8],
       [1, 5, 9]])