In [2]:
! pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [61]:
import numpy as n
# "python", "7", "numpy", 100, 9999
# 위의 값들을  Numpy 배열 선언하고 타입을 확인
custom_list = ["python", 7, "numpy", 100, 9999 ]
nd_array = n.array(custom_list)
type(nd_array), nd_array.dtype

# 0이 10개 채워진 1차원 배열 생성하여 출력
n.zeros(10,)

# 0이 10개 채워진 (5,5) 형태의 2차원 배열 생성하여 출력
n.zeros((5,5))

# 아래와 같은 결과가 나오도록 넘파이 배열을 만들어보자
# [0. 0.5 1.]
n.arange(0, 1+0.5, 0.5)

# 0부터 9까지 3제곱한 값을 넘파이 배열로 만들어보자
n.arange(10)**3

# - 위에서 만든 넘파이 배열에서 8을 출력해보자
a = n.arange(10)**3
a[2]

# - 27 64 125를 출력해보자
a[3:6]

# 64이상의 요소만 출력
a[a > 64]

# 경계가 1이고 내부가 0인 2차원 10x10배열을 만들자
z = n.zeros((10,10))
z[0] = 1 
z[-1] = 1
z[:,0] = 1
z[:,-1] = 1
# print(z)

z = n.ones((10, 10))
z[1:-1, 1:-1] = 0
# print(z)

z = n.zeros((10, 10))
z[[0, -1], :] = 1    
z[:, [0, -1]] = 1
# print(z)

# 5x3매트릭스에 3x2매트릭스를 곱해서 결과를 출력
n.ones((5,3)) @ n.ones((3,5))
# 행값이 0에서 4인 5x5 매트릭스 만들기
# array([[0., 1., 2., 3., 4.],
#        [0., 1., 2., 3., 4.],
#        [0., 1., 2., 3., 4.],
#        [0., 1., 2., 3., 4.],
#        [0., 1., 2., 3., 4.]])
z = n.zeros((5,5))
z_ = n.arange(5)
z = z + z_
z


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### 데이터 쪼개기
- n.hsplit()

In [110]:
# 0~11 2x6 행렬을 만들자
a = n.arange(12).reshape(2,6)
print(a)
n.hsplit(a, 3)
n.hsplit(a, 3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

In [115]:
print(a)
n.hsplit(a, (3,4)) # 2 ~ 5 마지막은 남은 것

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[3],
        [9]]),
 array([[ 4,  5],
        [10, 11]])]

In [121]:
print(a)
a = n.vsplit(a, 1)
print(a)
a = n.arange(18).reshape(3,6)
n.vsplit(a, (1,2))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])]


[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

### pandas (python data analysis library)
- 2차원 데이터를 효율적으로 가공할 수 있는 기능을 제공

In [123]:
! pip install pandas


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


## pandas 데이터 형식
- pandas = series와 series의 집합인 dataframe

### series
- 1차원 데이터
- index 데이터가 1:1로 맵핑되는 것
- 엑셀시트의 하나의 컬럼

### dataframe
- series가 여러개 모인 것

### series 생성방법
- 딕셔너리, 리스트로 생성 가능

In [4]:
import pandas as pd

dict_data = {'a':1, 'b':2, 'c':3}
series_data = pd.Series(dict_data, name= 'score')
series_data, type(series_data)


C:\Users\OWNER\AppData\Local\Temp\ipykernel_14596\537863858.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


(a    1
 b    2
 c    3
 Name: score, dtype: int64,
 pandas.core.series.Series)

In [163]:
list_data = ['2020-10-11', 3.14, 'ABC', 100, True]
series_data = pd.Series(list_data, index=[1,3,5,7,9], name='exam')
series_data, type(series_data)


(1    2020-10-11
 3          3.14
 5           ABC
 7           100
 9          True
 dtype: object,
 pandas.core.series.Series)

### dataframe
- 행과 열로 이루어진 2차원 배열

In [165]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9]}
df = pd.DataFrame(dict_data, index=[1,2,3], columns=['cv','cs','cg']) 
# 이미 컬럼이 지정되있기 때문에  NaN으로 값 변경
df, type(df)

(    cv   cs   cg
 1  NaN  NaN  NaN
 2  NaN  NaN  NaN
 3  NaN  NaN  NaN,
 pandas.core.frame.DataFrame)

In [5]:
titanic = pd.read_csv("data/titanic.csv")
type(titanic)

pandas.core.frame.DataFrame

In [169]:
titanic.columns
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [171]:
titanic.shape

(891, 12)

In [173]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [175]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [177]:
names = titanic['Name']
names.head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [198]:
titanic.Name
type(names), names.shape
passenger = titanic[['Sex', 'Age']]
passenger.head(10)
# passenger.shape



Sex   Age
0    male  22.0
1  female  38.0
2  female  26.0
3  female  35.0
4    male  35.0
5    male   NaN
6    male  54.0
7    male   2.0
8  female  27.0
9  female  14.0

In [201]:
passenger['Age'] > 35
above_35 = passenger[passenger['Age'] > 35]
above_35.head()

Sex   Age
1   female  38.0
6     male  54.0
11  female  58.0
13    male  39.0
15  female  55.0

isin() :  True/False

In [214]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [215]:
a = titanic['Pclass'].isin([1]).head() # 값이 있는지 없는지 판별.
titanic[titanic['Pclass'].isin([1])]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
11            12         1       1   
23            24         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
11       0    113783  26.5500         C103        S  
23       0    113788  35.5000           A6        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[216 rows x 12 columns]

In [225]:
# passenger 객체에서 20세에서 40세까지 정보를 추출
import numpy as np
# sol1
above_35 = passenger[(passenger['Age'] >= 20) & (passenger['Age'] <= 40)]
print(above_35)
# sol2
age2040 = passenger[passenger['Age'].isin(np.arange(20, 41))]
age2040

        Sex   Age
0      male  22.0
1    female  38.0
2    female  26.0
3    female  35.0
4      male  35.0
..      ...   ...
884    male  25.0
885  female  39.0
886    male  27.0
889    male  26.0
890    male  32.0

[400 rows x 2 columns]


Sex   Age
0      male  22.0
1    female  38.0
2    female  26.0
3    female  35.0
4      male  35.0
..      ...   ...
884    male  25.0
885  female  39.0
886    male  27.0
889    male  26.0
890    male  32.0

[389 rows x 2 columns]

In [229]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


### isna, notna
- isna() : 결측값은 True
- notna() : 결측값은 False

In [231]:
passenger.head(10)

Sex   Age
0    male  22.0
1  female  38.0
2  female  26.0
3  female  35.0
4    male  35.0
5    male   NaN
6    male  54.0
7    male   2.0
8  female  27.0
9  female  14.0

In [233]:
passenger['Age'].isna()[0:7]

0    False
1    False
2    False
3    False
4    False
5     True
6    False
Name: Age, dtype: bool

In [236]:
passenger[passenger['Age'].notna()]

Sex   Age
0      male  22.0
1    female  38.0
2    female  26.0
3    female  35.0
4      male  35.0
..      ...   ...
885  female  39.0
886    male  27.0
887  female  19.0
889    male  26.0
890    male  32.0

[714 rows x 2 columns]

##### 결측치 제거
dropna(axis = 1): 결측치 들어있는 행을 삭제
- axis = 1 : 열 삭제

In [242]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [244]:
# cabin이라는 변수에 name과 cabin 커럼을 추출해서 담아보자
cabin = titanic[['Name', 'Cabin']]
cabin.head()

Name Cabin
0                            Braund, Mr. Owen Harris   NaN
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   C85
2                             Heikkinen, Miss. Laina   NaN
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  C123
4                           Allen, Mr. William Henry   NaN

In [246]:
cabin[cabin['Cabin'].notna()].head()
cabin.head()


Name Cabin
0                            Braund, Mr. Owen Harris   NaN
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   C85
2                             Heikkinen, Miss. Laina   NaN
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  C123
4                           Allen, Mr. William Henry   NaN

In [248]:
cabin.dropna().head()

Name Cabin
1   Cumings, Mrs. John Bradley (Florence Briggs Th...   C85
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  C123
6                             McCarthy, Mr. Timothy J   E46
10                    Sandstrom, Miss. Marguerite Rut    G6
11                           Bonnell, Miss. Elizabeth  C103

In [250]:
cabin.dropna(axis=1).head() # 열 기준 삭제 axis = 0 은 행

Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                           Allen, Mr. William Henry

### Pandas에서 행과 열을 선택

```python
df.loc[col_index, row_index]

행 인덱스에서는 boolean indexing을 할 수 있다.

df.iloc[col_index, row_index]

```

In [252]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [255]:
titanic.loc[:5, 'Name']

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
Name: Name, dtype: object

In [307]:
# titanic.head()
# 3등석고객 중 살아있는 사람의 목록을 출력
titanic.head()
condition = (titanic['Survived'] == 1) & (titanic['Pclass'] == 3)
type(condition)
titanic.loc[condition]
a = titanic.loc[condition]
len(a)

0

In [309]:
# 35세 이상인 사람들의 이름과 나이를 출력
a = titanic['Age'] > 35 
a = titanic.loc[ titanic['Age'] < 35, ['Name', 'Age']] # 조건을 걸고 뒤에 원하는 값 설정 후 출력
# 원본 값은 변함이 없음

In [312]:
a.iloc[[1,2,3], 0] = 'No Name'
a

Name   Age
0                Braund, Mr. Owen Harris  22.0
2                                No Name  26.0
7                                No Name   2.0
8                                No Name  27.0
9    Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                   ...   ...
884               Sutehall, Mr. Henry Jr  25.0
886                Montvila, Rev. Juozas  27.0
887         Graham, Miss. Margaret Edith  19.0
889                Behr, Mr. Karl Howell  26.0
890                  Dooley, Mr. Patrick  32.0

[479 rows x 2 columns]

In [317]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1     False       3   
1            2     False       1   
2            3     False       3   
3            4     False       1   
4            5     False       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [320]:
titanic.iloc[:, :3]

PassengerId  Survived  Pclass
0              1     False       3
1              2     False       1
2              3     False       3
3              4     False       1
4              5     False       3
..           ...       ...     ...
886          887     False       2
887          888     False       1
888          889     False       3
889          890     False       1
890          891     False       3

[891 rows x 3 columns]

In [384]:
condition = (titanic['Survived'] == 1) & (titanic['Pclass'] == 3)
titanic.iloc[condition,3:4] = 'No Name'
titanic

titanic = pd.read_csv("data/titanic.csv")

In [385]:
titanic.iloc[condition, 3:4] = 'No Name'
titanic.head(30)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   
25           26         1       3   
26           27         0       3   
27           28         0       1   
28           29         1       3   
29           30         0       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                                             No Name  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8                                             No Name  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                                            No Name  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                                            No Name  female   NaN      0   
20                               Fynney, Mr. Joseph J    male  35.0      0   
21                              Beesley, Mr. Lawrence    male  34.0      0   
22                                            No Name  female  15.0      0   
23                       Sloper, Mr. William Thompson    male  28.0      0   
24                      Palsson, Miss. Torborg Danira  female   8.0      3   
25                                            No Name  female  38.0      1   
26                            Emir, Mr. Farred Chehab    male   NaN      0   
27                     Fortune, Mr. Charles Alexander    male  19.0      3   
28                                            No Name  female   NaN      0   
29                                Todoroff, Mr. Lalio    male   NaN      0   

    Parch            Ticket      Fare        Cabin Embarked  
0       0         A/5 21171    7.2500          NaN        S  
1       0          PC 17599   71.2833          C85        C  
2       0  STON/O2. 3101282    7.9250          NaN        S  
3       0            113803   53.1000         C123        S  
4       0            373450    8.0500          NaN        S  
5       0            330877    8.4583          NaN        Q  
6  

In [397]:

titanic.iloc[condition.values, :5] 

PassengerId  Survived  Pclass     Name     Sex
2              3         1       3  No Name  female
8              9         1       3  No Name  female
10            11         1       3  No Name  female
19            20         1       3  No Name  female
22            23         1       3  No Name  female
..           ...       ...     ...      ...     ...
838          839         1       3  No Name    male
855          856         1       3  No Name  female
858          859         1       3  No Name  female
869          870         1       3  No Name    male
875          876         1       3  No Name  female

[119 rows x 5 columns]

# pandas 데이터 통계
- df.mean() : 평균
- df.median() : 중간값
- df.describe() : 통계 데이터 요약
- df.agg([func1, func2...])

In [437]:
titanic = pd.read_csv("data/titanic.csv")

In [432]:
titanic['Age'].mean()
titanic['Age'].median()
titanic['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [440]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [434]:
titanic[['Age', 'Fare']].describe()
titanic.agg({'Age' : [ 'min', 'max', 'median'],
             'Fare' :[ 'min', 'max', 'mean'] })

Age        Fare
min      0.42    0.000000
max     80.00  512.329200
median  28.00         NaN
mean      NaN   32.204208

In [453]:

t = titanic[titanic.applymap(lambda x : isinstance(x, (int, float)))]
t1 = t.agg(['min', 'max', 'mean'] ) 
t1.head()


C:\Users\OWNER\AppData\Local\Temp\ipykernel_4612\3714692206.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  t = titanic[titanic.applymap(lambda x : isinstance(x, (int, float)))]


PassengerId  Survived    Pclass  Name  Sex        Age     SibSp  \
min           1.0  0.000000  1.000000   NaN  NaN   0.420000  0.000000   
max         891.0  1.000000  3.000000   NaN  NaN  80.000000  8.000000   
mean        446.0  0.383838  2.308642   NaN  NaN  29.699118  0.523008   

         Parch  Ticket        Fare  Cabin  Embarked  
min   0.000000     NaN    0.000000    NaN       NaN  
max   6.000000     NaN  512.329200    NaN       NaN  
mean  0.381594     NaN   32.204208    NaN       NaN

In [424]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [426]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [454]:
titanic.groupby(['Sex', 'Pclass'])[['Age', 'Fare']].agg( ['min', 'max', 'mean'] ) #앞의 것을 그룹화 하고, 원하는 컬럼값 출력

Age                      Fare                      
                min   max       mean      min       max        mean
Sex    Pclass                                                      
female 1       2.00  63.0  34.611765  25.9292  512.3292  106.125798
       2       2.00  57.0  28.722973  10.5000   65.0000   21.970121
       3       0.75  63.0  21.750000   6.7500   69.5500   16.118810
male   1       0.92  80.0  41.281386   0.0000  512.3292   67.226127
       2       0.67  70.0  30.740707   0.0000   73.5000   19.741782
       3       0.42  74.0  26.507589   0.0000   69.5500   12.661633

In [457]:
survied = titanic.groupby('Sex')['Survived'].mean()
(survied*100)

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

In [459]:
titanic.pivot_table(index='Sex', values='Survived', aggfunc=['sum'])

sum
       Survived
Sex            
female      233
male        109

In [466]:
# 성별로 좌석등급별 나이와 생존률의 평균
a = titanic.groupby(['Sex', 'Pclass'])[['Age', 'Survived']].mean()

In [467]:
a

Age  Survived
Sex    Pclass                     
female 1       34.611765  0.968085
       2       28.722973  0.921053
       3       21.750000  0.500000
male   1       41.281386  0.368852
       2       30.740707  0.157407
       3       26.507589  0.135447

In [474]:
a.iloc[:,1]= a['Survived']*100 # 따로 추출해서 변경
a

Age     Survived
Sex    Pclass                        
female 1       34.611765  9680.851064
       2       28.722973  9210.526316
       3       21.750000  5000.000000
male   1       41.281386  3688.524590
       2       30.740707  1574.074074
       3       26.507589  1354.466859

In [476]:
titanic['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [478]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [482]:
titanic['Cabin' ].value_counts(dropna=False) 

Cabin
NaN            687
C23 C25 C27      4
G6               4
B96 B98          4
C22 C26          3
              ... 
E34              1
C7               1
C54              1
E36              1
C148             1
Name: count, Length: 148, dtype: int64

In [6]:
titanic.groupby(["Sex", "Pclass"])['Survived'].value_counts()


Sex     Pclass  Survived
female  1       1            91
                0             3
        2       1            70
                0             6
        3       0            72
                1            72
male    1       0            77
                1            45
        2       0            91
                1            17
        3       0           300
                1            47
Name: count, dtype: int64